version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch

    working_directory: ~/monProfil

    steps:
      - checkout

      - restore_cache:
          name: Restore yarn cache
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          name: Save yarn cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
        
      - run:
          name: Unit tests
          command: yarn test
