version: 2

defaults:
  workspace_root: &workspace_root
    ~/isogeo-profile

  nodejs_container: &nodejs_container
    working_directory: *workspace_root
    docker:
      - image: circleci/node:8-browsers

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - isogeo-profile-node-{{ checksum "yarn.lock" }}
        - isogeo-profile-

jobs:
  checkout:
    <<: *nodejs_container
    steps:
      - checkout

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  install:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - restore_cache:
          name: Restore yarn cache
          keys:
            - isogeo-profile-yarn-{{ checksum "yarn.lock" }}
            - isogeo-profile-yarn-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          name: Save yarn cache
          key: isogeo-profile-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/

      - save_cache:
          name: Save node_modules cache
          key: isogeo-profile-node-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/

  build:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - restore_cache:
          name: Restore yarn cache
          keys:
            - isogeo-profile-yarn-{{ checksum "yarn.lock" }}
            - isogeo-profile-yarn-

      - run:
          name: Angular build
          command: yarn ng -- build --prod --aot --no-progress

      - store_artifacts:
          path: ./dist
          prefix: build

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist/

  test:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - restore_cache:
          name: Restore yarn cache
          keys:
            - isogeo-profile-yarn-{{ checksum "yarn.lock" }}
            - isogeo-profile-yarn-

      - run:
          name: Angular test
          command: yarn test --no-progress --code-coverage

      - store_artifacts:
          path: test-results.xml
          prefix: tests

      - run:
          name: angular-lint
          command: yarn lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml

      - store_artifacts:
          path: tslint.xml
          prefix: lint

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist/

workflows:
  version: 2

  push:
    jobs:
      - checkout

      - install:
          requires:
            - checkout

      - build:
          requires:
            - install

#      - test:
#          requires:
#            - build
